version: "3.9"

services:
  database:
    image: postgres:13.3-alpine
    container_name: post_it_db
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  data:
