POST http://localhost:3000/api/auth/register

Content-Type: application/json

{
  "email": "dicha.arkana03@gmail.com",
  "username": "elianiva",
  "password": "thisismypassword"
}

# -------------------------------------------

POST http://localhost:3000/api/auth/login

Content-Type: application/json

{
  "email": "dicha.arkana03@gmail.com",
  "username": "elianiva",
  "password": "thisismypassword"
}
